# Generated by Django 4.0.5 on 2022-06-28 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=60)),
                ('mobile_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitee_name', models.CharField(max_length=60)),
                ('visitee_status', models.CharField(max_length=4)),
                ('visitor_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=12)),
                ('id_or_passport', models.CharField(max_length=20)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.organization')),
                ('visitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.visitee')),
            ],
        ),
    ]
